// This file is automatically generated by ExtractBlobData.
// To regenerate it, run: ExtractBlobData "C:\Path\To\Steam"

using System.Collections.Generic;

namespace Sledge.Settings.GameDetection.GameFiles
{
    public static class SteamGames
    {
        public static List<SteamGame> Games { get; set; }

        static SteamGames()
        {
            Games = new List<SteamGame>
                        {
                            new SteamGame(10, "Counter-Strike", new List<string>
                                                         {
                                                             "Counter-Strike",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life",
                                                         }),
                            new SteamGame(20, "Team Fortress Classic", new List<string>
                                                         {
                                                             "Team Fortress Classic",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life",
                                                         }),
                            new SteamGame(30, "Day of Defeat", new List<string>
                                                         {
                                                             "Day of Defeat",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life",
                                                         }),
                            new SteamGame(40, "Deathmatch Classic", new List<string>
                                                         {
                                                             "Deathmatch Classic",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life",
                                                         }),
                            new SteamGame(50, "Half-Life: Opposing Force", new List<string>
                                                         {
                                                             "Opposing Force",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life",
                                                         }),
                            new SteamGame(60, "Ricochet", new List<string>
                                                         {
                                                             "Ricochet",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life",
                                                         }),
                            new SteamGame(70, "Half-Life", new List<string>
                                                         {
                                                             "Half-Life",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life Base Content",
                                                         }),
                            new SteamGame(80, "Condition Zero", new List<string>
                                                         {
                                                             "Condition Zero",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life",
                                                             "Counter-Strike",
                                                         }),
                            new SteamGame(100, "Condition Zero Deleted Scenes", new List<string>
                                                         {
                                                             "Condition Zero Deleted Scenes",
                                                             "Half-Life Engine",
                                                             "Platform",
                                                             "Half-Life",
                                                             "Counter-Strike",
                                                             "Condition Zero Deleted Scenes Base Content",
                                                             "Condition Zero Deleted Scenes Models",
                                                             "Condition Zero Deleted Scenes Sounds",
                                                         }),
                            new SteamGame(130, "Half-Life: Blue Shift", new List<string>
                                                         {
                                                             "Half-Life Blue Shift",
                                                             "Platform",
                                                             "Half-Life Engine",
                                                             "Half-Life",
                                                         }),
                            new SteamGame(220, "Half-Life 2", new List<string>
                                                         {
                                                             "Half-Life 2",
                                                             "Source 2007 Binaries 2",
                                                             "Half-Life 2 Game Dialog",
                                                             "Half-Life 2 2007 Base Content",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Source Engine",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "Half-Life 2 Content",
                                                         }),
                            new SteamGame(240, "Counter-Strike: Source", new List<string>
                                                         {
                                                             "Counter-Strike Source",
                                                             "Counter-Strike Source Binaries",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Counter-Strike Source Client",
                                                             "Counter-Strike Source Shared",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "OrangeBox Media",
                                                         }),
                            new SteamGame(280, "Half-Life: Source", new List<string>
                                                         {
                                                             "Half-Life Source",
                                                             "Source Engine",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                         }),
                            new SteamGame(300, "Day of Defeat: Source", new List<string>
                                                         {
                                                             "Day of Defeat Source",
                                                             "Multiplayer OB Binaries",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                         }),
                            new SteamGame(320, "Half-Life 2: Deathmatch", new List<string>
                                                         {
                                                             "Half-Life 2 Deathmatch",
                                                             "Multiplayer OB Binaries",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                         }),
                            new SteamGame(340, "Half-Life 2: Lost Coast", new List<string>
                                                         {
                                                             "Half-Life 2 LostCoast",
                                                             "Half-Life 2 Game Dialog",
                                                             "Source Engine",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "LostCoast Content",
                                                         }),
                            new SteamGame(360, "Half-Life Deathmatch: Source", new List<string>
                                                         {
                                                             "Half-Life Deathmatch Source",
                                                             "Base Source Engine 2",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "Half-Life Source",
                                                             "Half-Life Source Deathmatch client",
                                                         }),
                            new SteamGame(380, "Half-Life 2: Episode One", new List<string>
                                                         {
                                                             "Half-Life 2 Episode One",
                                                             "Source 2007 Binaries 2",
                                                             "Episode One 2007 Content",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Episodic 2007 Shared",
                                                             "Episode 1 Shared",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                         }),
                            new SteamGame(400, "Portal", new List<string>
                                                         {
                                                             "Portal",
                                                             "Source 2007 Binaries 2",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Portal Content",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "OrangeBox Media",
                                                         }),
                            new SteamGame(420, "Half-Life 2: Episode Two", new List<string>
                                                         {
                                                             "Half-Life 2 Episode Two",
                                                             "Source 2007 Binaries 2",
                                                             "Episode Two Content",
                                                             "Episode Two Maps",
                                                             "Episode Two Materials",
                                                             "Episodic 2007 Shared",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "Episode 1 Shared",
                                                             "OrangeBox Media",
                                                         }),
                            new SteamGame(440, "Team Fortress 2", new List<string>
                                                         {
                                                             "Team Fortress 2",
                                                             "Multiplayer OB Binaries",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Team Fortress 2 Content",
                                                             "Team Fortress 2 Materials",
                                                             "Team Fortress 2 Client Content",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "OrangeBox Media",
                                                         }),
                            new SteamGame(500, "Left 4 Dead", new List<string>
                                                         {
                                                             "left 4 dead",
                                                             "Left 4 Dead binaries",
                                                             "Left 4 Dead base",
                                                             "Left 4 Dead client binary",
                                                             "Left 4 Dead sound",
                                                         }),
                            new SteamGame(550, "Left 4 Dead 2", new List<string>
                                                         {
                                                             "Left 4 Dead 2",
                                                             "left 4 dead 2 common",
                                                             "left 4 dead 2 client",
                                                         }),
                            new SteamGame(570, "Dota 2", new List<string>
                                                         {
                                                             "dota 2 beta",
                                                             "dota 2 beta content",
                                                             "dota 2 beta client",
                                                             "dota 2 beta win32 content",
                                                         }),
                            new SteamGame(620, "Portal 2", new List<string>
                                                         {
                                                             "Portal 2",
                                                             "portal 2 common",
                                                             "portal 2 win content",
                                                             "portal 2 client binaries",
                                                         }),
                            new SteamGame(630, "Alien Swarm", new List<string>
                                                         {
                                                             "Alien Swarm",
                                                             "alien swarm content",
                                                         }),
                            new SteamGame(1800, "Counter-Strike: Global Offensive", new List<string>
                                                         {
                                                             "Counter-Strike_ Global Offensive",
                                                             "winui",
                                                             "SourceInit",
                                                         }),
                            new SteamGame(4000, "Garry's Mod", new List<string>
                                                         {
                                                             "GarrysMod",
                                                             "GarrysMod Content",
                                                             "Multiplayer OB Binaries",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "OrangeBox Media",
                                                         }),
                            new SteamGame(211, "Source SDK", new List<string>
                                                         {
                                                             "SourceSDK",
                                                         }),
                            new SteamGame(215, "Source SDK Base 2006", new List<string>
                                                         {
                                                             "Source SDK Base",
                                                             "Base Source Engine 2",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                         }),
                            new SteamGame(218, "Source SDK Base - Orange Box", new List<string>
                                                         {
                                                             "Source SDK Base 2007",
                                                             "Source 2007 Binaries",
                                                             "Source 2007 Shared Materials",
                                                             "Source 2007 Shared Models",
                                                             "Source 2007 Shared Sounds",
                                                             "Source Materials",
                                                             "Source Models",
                                                             "Source Sounds",
                                                             "Source SDK Base",
                                                             "Base Source Engine 2",
                                                         }),
                            new SteamGame(513, "Left 4 Dead Authoring Tools", new List<string>
                                                         {
                                                             "Left 4 Dead",
                                                             "Left 4 Dead binaries",
                                                             "Left 4 Dead base",
                                                             "Left 4 Dead client binary",
                                                             "Left 4 Dead sound",
                                                         }),
                            new SteamGame(629, "Portal 2 Authoring Tools - Beta", new List<string>
                                                         {
                                                             "Portal 2",
                                                             "portal 2 common",
                                                         }),
                        };
        }
    }
}
